# Generated by Django 5.2.5 on 2026-04-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_fix_reopened_completed_tv_seasons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeImportScanState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seed_mal_id", models.CharField(max_length=36)),
                (
                    "profile_key",
                    models.CharField(
                        choices=[("continuity", "Continuity"), ("satellites", "Satellites"), ("complete", "Complete")],
                        max_length=20,
                    ),
                ),
                ("next_scan_at", models.DateTimeField()),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_change_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("consecutive_stable_scans", models.PositiveIntegerField(default=0)),
                ("consecutive_error_count", models.PositiveIntegerField(default=0)),
                ("component_root_mal_id", models.CharField(blank=True, default="", max_length=36)),
                ("last_component_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["profile_key", "next_scan_at"], name="app_animeimportscanstate_due_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "seed_mal_id", "profile_key"),
                        name="app_animeimportscanstate_unique_seed_profile",
                    ),
                ],
            },
        ),
    ]
