# Generated by Django 5.2.8 on 2026-06-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_anime_franchise_discovery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeImportComponentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.CharField(max_length=36)),
                ("component_root_mal_id", models.CharField(max_length=36)),
                ("component_size", models.PositiveIntegerField(default=0)),
                (
                    "source_profile_key",
                    models.CharField(
                        choices=[
                            ("continuity", "Continuity"),
                            ("satellites", "Satellites"),
                            ("complete", "Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "component_root_mal_id"],
                        name="app_anicmpmem_user_root_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "media_id"),
                        name="app_anicmpmem_user_media_uniq",
                    ),
                ],
            },
        ),
    ]
