# Generated by Django 5.2.14 on 2026-06-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_anime_franchise_discovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeLocalSeriesMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=36)),
                ('root_media_id', models.CharField(max_length=36)),
                ('group_kind', models.CharField(choices=[('main_continuity', 'Main continuity'), ('alternative_branch', 'Alternative branch'), ('spin_off_branch', 'Spin-off branch'), ('singleton', 'Singleton')], max_length=24)),
                ('context_parent_media_id', models.CharField(blank=True, default='', max_length=36)),
                ('context_relation_type', models.CharField(blank=True, default='', max_length=50)),
                ('component_size', models.PositiveIntegerField()),
                ('source_profile_key', models.CharField(max_length=50)),
                ('resolver_version', models.CharField(max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'root_media_id'], name='app_anilocseries_root_idx'), models.Index(fields=['user', 'group_kind'], name='app_anilocseries_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'media_id', 'source_profile_key', 'resolver_version'), name='app_anilocseries_scope_uniq')],
            },
        ),
    ]
