# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_alter_animeseriesviewmembership_projection_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeFranchiseMaintenanceScanState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seed_mal_id", models.CharField(max_length=36)),
                ("component_root_mal_id", models.CharField(blank=True, default="", max_length=36)),
                ("next_scan_at", models.DateTimeField()),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_change_at", models.DateTimeField(blank=True, null=True)),
                ("last_result_fingerprint", models.CharField(blank=True, default="", max_length=128)),
                ("last_error", models.TextField(blank=True, default="")),
                ("consecutive_stable_scans", models.PositiveIntegerField(default=0)),
                ("consecutive_error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="animefranchisemaintenancescanstate",
            constraint=models.UniqueConstraint(fields=("user", "seed_mal_id"), name="app_af_maint_state_unique"),
        ),
        migrations.AddIndex(
            model_name="animefranchisemaintenancescanstate",
            index=models.Index(fields=["next_scan_at"], name="app_af_maint_due_idx"),
        ),
        migrations.AddIndex(
            model_name="animefranchisemaintenancescanstate",
            index=models.Index(fields=["user", "component_root_mal_id"], name="app_af_maint_root_idx"),
        ),
        migrations.AddIndex(
            model_name="animefranchisemaintenancescanstate",
            index=models.Index(fields=["user", "seed_mal_id"], name="app_af_maint_seed_idx"),
        ),
    ]
