# Generated by Django 5.2.16 on 2026-08-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeMetadataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.PositiveBigIntegerField()),
                ("source", models.CharField(default="mal", max_length=16)),
                ("canonical_title", models.CharField(max_length=255, null=True)),
                ("alternative_title_en", models.CharField(max_length=255, null=True)),
                ("image", models.URLField(max_length=500, null=True)),
                ("synopsis", models.TextField(null=True)),
                ("genres", models.JSONField(default=list)),
                ("score", models.FloatField(null=True)),
                ("score_count", models.PositiveIntegerField(null=True)),
                ("episode_count", models.PositiveIntegerField(null=True)),
                ("media_type", models.CharField(max_length=32, null=True)),
                ("start_date", models.CharField(max_length=10, null=True)),
                ("end_date", models.CharField(max_length=10, null=True)),
                ("status", models.CharField(max_length=64, null=True)),
                ("runtime", models.PositiveIntegerField(null=True)),
                ("studios", models.JSONField(default=list)),
                ("season_year", models.PositiveIntegerField(null=True)),
                ("season_name", models.CharField(max_length=16, null=True)),
                ("broadcast_day", models.CharField(max_length=32, null=True)),
                ("broadcast_time", models.CharField(max_length=8, null=True)),
                ("source_material", models.CharField(max_length=64, null=True)),
                ("relations", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("fetched_at", models.DateTimeField(null=True)),
                ("refresh_after", models.DateTimeField(db_index=True, null=True)),
                ("last_refresh_attempt_at", models.DateTimeField(null=True)),
                ("last_refresh_error_at", models.DateTimeField(null=True)),
                ("last_error_message", models.TextField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "media_id"),
                        name="anime_metadata_unique_source_media",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("media_id__gt", 0)),
                        name="anime_metadata_positive_media_id",
                    ),
                ],
            },
        ),
    ]
