# Generated by Django 5.2.11 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_user_watch_provider_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="entry_added_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Receive notifications when a new entry is added",
            ),
        ),
    ]
